"""B19: 100 machine-learning hypotheses on the hourly perp panel + cross-source primitives (registered 2026-10-01).

Every hypothesis is one (target x feature set x model) cell of a pre-declared grid, 5 x 4 x 5 = 100:
  targets   xs24   24h BTC-residual return, cross-sectional rank          -> 24h quintile L/S (3 staggered books, b7_lib.long_short)
            xs72   72h BTC-residual return, cross-sectional rank          -> 72h hold-band quintile L/S (b18_disc2.book)
            pump24 P(high within 24h >= +10%)                              -> 24h quintile L/S on the prediction, sign from discovery
            dump24 P(low within 24h <= -10%)                               -> same
            vol24  rank of |24h return| (magnitude)                         -> same (low-vol / high-vol tilt, sign from discovery)
  features  base   price/volume/volatility/beta/range (the known factors and their relatives)
            pos    base + funding, OI, long/short ratios, taker flow, trade count
            xven   pos + spot / Upbit / Bithumb divergences and volume shares
            all    xven + on-chain flows, book depth, market state (breadth, BTC trend, market vol)
  models    ridge  linear (Ridge / logistic), the baseline every complex model must beat
            lgbm   gradient boosting (LambdaRank for the cross-sectional targets, binary/regression otherwise)
            cat    CatBoost (ordered boosting, symmetric trees)
            mlp    3-layer torch MLP (SiLU, dropout, AdamW)
            gru    GRU over the last 12 eight-hour steps (4 days) of the feature vector
Protocol: features are cross-sectional ranks at each 8h row (bar close, known at t). Walk-forward, expanding window,
quarterly refits from 2024-10-01; training rows are purged so that t + horizon <= test start. Every prediction is
out-of-sample. DISCOVERY = predictions 2024-10..2025-12, VALIDATION = predictions 2026. Trading direction is fixed on
discovery. Pass = BH q=0.10 across all 100 on the discovery daily-net p-value AND validation mean daily net with a
bootstrap 95% CI above 0 AND same sign. Costs: fee 0.05% + slippage by 24h volume on every weight change, funding paid.
  OMP_NUM_THREADS=6 .venv/bin/python -u -W ignore scripts/b19_ml.py register|run [ids...]|report
Outputs: research/batch_B19_registry.yaml, data/reports/b19/H###.json, data/cache/b19/H###.npy (float16 predictions)."""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import b7_lib as L  # noqa: E402
import disc_engine as DE  # noqa: E402

OUT, CACHE = ROOT / "data/reports/b19", ROOT / "data/cache/b19"
REG = ROOT / "research/batch_B19_registry.yaml"
TARGETS = ["xs24", "xs72", "pump24", "dump24", "vol24"]
FSETS = ["base", "pos", "xven", "all"]
MODELS = ["ridge", "lgbm", "cat", "mlp", "gru"]
H_OF = {"xs24": 24, "xs72": 72, "pump24": 24, "dump24": 24, "vol24": 24}
BINARY = {"pump24", "dump24"}
T0 = int(pd.Timestamp("2024-03-15").timestamp())
BLOCKS = [int(pd.Timestamp(d).timestamp()) for d in
          ("2024-10-01", "2025-01-01", "2025-04-01", "2025-07-01", "2025-10-01", "2026-01-01", "2026-04-01", "2026-07-01", "2026-10-01")]
VAL0 = DE.VAL0
SEQ = 12


def grid():
    out, k = [], 1
    for t in TARGETS:
        for f in FSETS:
            for m in MODELS:
                out.append({"id": f"H{k:03d}", "target": t, "features": f, "model": m}); k += 1
    return out


DESC_T = {"xs24": "the 24h BTC-residual cross-sectional return", "xs72": "the 72h BTC-residual cross-sectional return",
          "pump24": "a +10% spike within 24h", "dump24": "a -10% drop within 24h", "vol24": "the size of the next 24h move"}
DESC_F = {"base": "price/volume/volatility features", "pos": "price/volume + derivatives positioning (funding, OI, long/short, taker flow)",
          "xven": "price/volume + positioning + cross-venue (spot, Upbit, Bithumb) features", "all": "every source incl. on-chain, book depth and market state"}
DESC_M = {"ridge": "a linear model", "lgbm": "LightGBM (LambdaRank / GBDT)", "cat": "CatBoost", "mlp": "a 3-layer neural net",
          "gru": "a GRU sequence model over 4 days of history"}


def register():
    lines = ["# B19 machine-learning registry (registered 2026-10-01, before any run). Generated by scripts/b19_ml.py register.",
             "protocol: see the scripts/b19_ml.py docstring (walk-forward quarterly refits, purged, discovery 2024-10..2025-12, validation 2026,",
             "  pass = BH q=0.10 on discovery + validation daily-net CI above 0, same sign; costs and funding included)", "hypotheses:"]
    for h in grid():
        lines.append(f"  - id: {h['id']}")
        lines.append(f"    target: {h['target']}\n    features: {h['features']}\n    model: {h['model']}")
        lines.append(f"    statement: \"{DESC_M[h['model']]} trained on {DESC_F[h['features']]} predicts {DESC_T[h['target']]} out of sample, "
                     f"and a quintile long-short on its prediction earns more than costs in 2026\"")
    REG.write_text("\n".join(lines) + "\n")
    print("registered", len(grid()), REG)


# ------------------------------------------------------------------ data
_cache = {}


def rows8():
    ts, _, _ = L.data()
    return np.flatnonzero((ts % (8 * 3600) == 0) & (ts >= T0))


def cs_rank(A):
    return (pd.DataFrame(A).rank(axis=1, pct=True).to_numpy(np.float32) - 0.5)


def feature_cube(fset):
    if fset in _cache:
        return _cache[fset]
    ts, codes, X = L.data()
    R = rows8()
    P = lambda k: np.asarray(DE.prim(k))
    lc, r1, qv = X["lc"], X["r1"], np.nan_to_num(X["qv"])
    feats = {}
    add = lambda n, A: feats.__setitem__(n, np.asarray(A, np.float32)[R])
    for w in (1, 8, 24, 72, 168, 672):
        add(f"r{w}", lc - L.lag(lc, w))
    add("rv24", L.SD(r1, 24)); add("rv168", L.SD(r1, 168)); add("max1h_7d", L.MX(r1, 168)); add("min1h_7d", L.MN(r1, 168))
    add("log_dv24", np.log1p(X["dv24"])); add("vol_surprise", np.log1p(L.S(qv, 24)) - np.log1p(L.S(qv, 168) / 7.0))
    add("levy", X["levy"]); add("corr_btc", X["corr_btc"]); add("beta", X["beta"]); add("age", np.log1p(X["age"]))
    add("dist_hi7", lc - L.MX(lc, 168)); add("dist_lo7", lc - L.MN(lc, 168)); add("dist_hi30", lc - L.MX(lc, 720))
    if fset in ("pos", "xven", "all"):
        f8 = X["f8"]; oi = np.log(P("m_oi_usd")); tp, gl, tr = P("m_ls_top_pos"), P("m_ls_global"), P("m_taker_ratio")
        add("f8", f8); add("f8_z", DE.rollz(f8)); add("oi_chg24", DE.diffk(oi, 24)); add("oi_chg168", DE.diffk(oi, 168))
        add("oi_to_vol", oi - np.log(X["dv24"])); add("ls_global", np.log(gl)); add("ls_top_pos", np.log(tp))
        add("smart_minus_crowd", np.log(tp) - np.log(gl)); add("taker_ratio", np.log(tr))
        add("taker_share24", DE.rollmean(DE.share(X["tbq"], X["qv"] - X["tbq"]), 24)); add("trades_surprise", np.log1p(L.S(X["n"], 24)) - np.log1p(L.S(X["n"], 168) / 7.0))
    if fset in ("xven", "all"):
        sp, up, bt = P("sp_lc"), P("up_lc"), P("bt_lc")
        add("div_sp_1h", DE.diffk(sp, 1) - DE.diffk(lc, 1)); add("div_sp_24h", DE.diffk(sp, 24) - DE.diffk(lc, 24)); add("basis_sp", sp - lc)
        add("div_up_24h", DE.diffk(up, 24) - DE.diffk(lc, 24)); add("div_bt_24h", DE.diffk(bt, 24) - DE.diffk(lc, 24)); add("prem_up_z", DE.rollz(up - lc))
        uq, bq, sq = P("up_qv"), P("bt_qv"), P("sp_qv")
        add("vshare_sp", DE.share(sq, qv)); add("vshare_up", DE.share(uq, qv)); add("vshare_bt", DE.share(bq, qv))
        kq = np.nan_to_num(uq) + np.nan_to_num(bq); kq[kq == 0] = np.nan; add("vshare_kr", DE.share(kq, qv))
    if fset == "all":
        oin, oout = P("oc_inflow"), P("oc_outflow")
        add("oc_net24", DE.rollmean(oin - oout, 24)); add("oc_inflow_z", DE.rollz(oin))
        add("depth_imb1", P("dp_imb_1")); add("depth_imb5", P("dp_imb_5"))
    F = np.stack([cs_rank(v) for v in feats.values()], -1)                 # rows x N x k, each in [-0.5, 0.5]
    if fset == "all":                                                        # market state, broadcast (not ranked)
        up24 = np.where(X["U"], (lc - L.lag(lc, 24)) > 0, np.nan)
        bi = codes.index("BTCUSDT")
        ms = [np.nanmean(up24, 1) - 0.5, (lc - L.lag(lc, 24))[:, bi] * 10, np.nanmean(np.where(X["U"], L.SD(r1, 24), np.nan), 1) * 50]
        F = np.concatenate([F, np.stack([np.repeat(np.asarray(m, np.float32)[R][:, None], F.shape[1], 1) for m in ms], -1)], -1)
    names = list(feats) + (["breadth24", "btc_r24", "mkt_vol24"] if fset == "all" else [])
    _cache[fset] = (F.astype(np.float32), names)
    return _cache[fset]


def targets():
    if "tg" in _cache:
        return _cache["tg"]
    ts, codes, X = L.data()
    R = rows8(); bi = codes.index("BTCUSDT")
    lc, h, lo = X["lc"], X["h"], X["l"]
    f24 = L.lag(lc, -24) - lc; f72 = L.lag(lc, -72) - lc
    beta = np.nan_to_num(X["beta"])
    res24, res72 = f24 - beta * f24[:, [bi]], f72 - beta * f72[:, [bi]]
    hh = pd.DataFrame(h).iloc[::-1].rolling(24, min_periods=24).max().iloc[::-1].shift(-1).to_numpy()   # max high of the next 24 bars
    ll = pd.DataFrame(lo).iloc[::-1].rolling(24, min_periods=24).min().iloc[::-1].shift(-1).to_numpy()
    c = X["c"]
    tg = {"xs24": res24, "xs72": res72,
          "pump24": np.where(np.isfinite(hh), (hh / c - 1 >= 0.10).astype(np.float32), np.nan),
          "dump24": np.where(np.isfinite(ll), (ll / c - 1 <= -0.10).astype(np.float32), np.nan),
          "vol24": np.abs(f24)}
    tg = {k: np.asarray(v, np.float32)[R] for k, v in tg.items()}
    tg["mask"] = (X["U"][R] & np.isfinite(tg["xs24"]))
    tg["ts"] = ts[R]
    _cache["tg"] = tg
    return tg


# ------------------------------------------------------------------ models
def fit_predict(model, target, Ftr, ytr, gtr, Fte, seq_tr=None, seq_te=None):
    binary = target in BINARY
    if model == "ridge":
        from sklearn.linear_model import LogisticRegression, Ridge
        A, B = np.nan_to_num(Ftr), np.nan_to_num(Fte)
        if binary:
            m = LogisticRegression(C=0.1, max_iter=300).fit(A, ytr); return m.predict_proba(B)[:, 1]
        return Ridge(alpha=10.0).fit(A, ytr).predict(B)
    if model == "lgbm":
        import lightgbm as lgb
        kw = dict(n_estimators=400, learning_rate=0.03, num_leaves=31, min_child_samples=200, subsample=0.8, subsample_freq=1,
                  colsample_bytree=0.8, reg_lambda=1.0, n_jobs=6, verbose=-1)
        if target in ("xs24", "xs72"):
            rel = np.clip(((ytr + 0.5) * 5).astype(int), 0, 4)                 # quintile relevance within each row
            m = lgb.LGBMRanker(objective="lambdarank", **kw).fit(Ftr, rel, group=gtr); return m.predict(Fte)
        if binary:
            return lgb.LGBMClassifier(**kw).fit(Ftr, ytr).predict_proba(Fte)[:, 1]
        return lgb.LGBMRegressor(**kw).fit(Ftr, ytr).predict(Fte)
    if model == "cat":
        from catboost import CatBoostClassifier, CatBoostRegressor
        kw = dict(iterations=400, depth=6, learning_rate=0.05, thread_count=6, verbose=0, random_seed=7)
        if binary:
            return CatBoostClassifier(**kw).fit(Ftr, ytr).predict_proba(Fte)[:, 1]
        return CatBoostRegressor(**kw).fit(Ftr, ytr).predict(Fte)
    import torch
    torch.set_num_threads(1); torch.manual_seed(7)   # >1 thread deadlocks when lightgbm's libomp is loaded in the same process (hung 2026-10-01)
    dev = "cpu"                                                                 # MPS caused a kernel panic on 2026-09-29
    k = Ftr.shape[-1]
    if model == "mlp":
        net = torch.nn.Sequential(torch.nn.Linear(k, 128), torch.nn.SiLU(), torch.nn.Dropout(0.1), torch.nn.Linear(128, 64), torch.nn.SiLU(),
                                  torch.nn.Dropout(0.1), torch.nn.Linear(64, 1))
        Xtr, Xte = torch.tensor(np.nan_to_num(Ftr)), torch.tensor(np.nan_to_num(Fte))
    else:
        class G(torch.nn.Module):
            def __init__(s):
                super().__init__(); s.g = torch.nn.GRU(k, 64, batch_first=True); s.h = torch.nn.Linear(64, 1)
            def forward(s, x):
                o, _ = s.g(x); return s.h(o[:, -1])
        net = G(); Xtr, Xte = torch.tensor(np.nan_to_num(seq_tr)), torch.tensor(np.nan_to_num(seq_te))
    y = torch.tensor(ytr.astype(np.float32))[:, None]
    lossf = torch.nn.BCEWithLogitsLoss() if binary else torch.nn.MSELoss()
    opt = torch.optim.AdamW(net.parameters(), lr=1e-3, weight_decay=1e-4)
    n, bs = len(Xtr), 4096
    for _ in range(4 if model == "mlp" else 3):
        net.train()
        for i in torch.randperm(n).split(bs):
            opt.zero_grad(); loss = lossf(net(Xtr[i]), y[i]); loss.backward(); opt.step()
    net.eval()
    with torch.no_grad():
        out = torch.cat([net(Xte[i:i + 16384]) for i in range(0, len(Xte), 16384)]).squeeze(1)
    return (torch.sigmoid(out) if binary else out).numpy()


def run_one(h):
    OUT.mkdir(parents=True, exist_ok=True); CACHE.mkdir(parents=True, exist_ok=True)
    if (OUT / f"{h['id']}.json").exists():
        return json.load(open(OUT / f"{h['id']}.json"))
    t_start = time.time()
    F, names = feature_cube(h["features"]); tg = targets()
    ts, mask, Hh = tg["ts"], tg["mask"], H_OF[h["target"]]
    y = tg[h["target"]]
    if h["target"] in ("xs24", "xs72", "vol24"):
        y = cs_rank(np.where(mask, y, np.nan))
    nR, N, k = F.shape
    P = np.full((nR, N), np.nan, np.float32)
    for b0, b1 in zip(BLOCKS[:-1], BLOCKS[1:]):
        tr_rows = np.flatnonzero(ts + Hh * 3600 <= b0)
        te_rows = np.flatnonzero((ts >= b0) & (ts < b1))
        if len(te_rows) == 0 or len(tr_rows) < 60:
            continue
        mtr = mask[tr_rows] & np.isfinite(y[tr_rows]); mte = mask[te_rows]
        ri, ci = np.nonzero(mtr); rt, ct = np.nonzero(mte)
        Ftr, Fte = F[tr_rows[ri], ci], F[te_rows[rt], ct]
        ytr = y[tr_rows[ri], ci]
        gtr = np.bincount(ri, minlength=len(tr_rows)); gtr = gtr[gtr > 0]
        seq_tr = seq_te = None
        if h["model"] == "gru":
            def seqs(rows_abs, cols):
                idx = rows_abs[:, None] - np.arange(SEQ - 1, -1, -1)[None, :]
                return F[np.maximum(idx, 0), cols[:, None]]
            seq_tr, seq_te = seqs(tr_rows[ri], ci), seqs(te_rows[rt], ct)
        p = fit_predict(h["model"], h["target"], Ftr, ytr, gtr, Fte, seq_tr, seq_te)
        P[te_rows[rt], ct] = p
    np.save(CACHE / f"{h['id']}.npy", P.astype(np.float16))
    res = evaluate(h, P)
    res["seconds"] = round(time.time() - t_start, 1)
    json.dump(res, open(OUT / f"{h['id']}.json", "w"), indent=1, default=float)
    return res


def evaluate(h, P):
    ts_all, _, X = L.data()
    R = rows8()
    full = np.full(X["c"].shape, np.nan, np.float32); full[R] = P
    tg = targets(); ts = tg["ts"]
    real = tg["xs72" if h["target"] == "xs72" else "xs24"]
    disc_rows, val_rows = (ts >= BLOCKS[0]) & (ts < VAL0), ts >= VAL0

    def ic(rows):
        out = []
        for i in np.flatnonzero(rows):
            m = tg["mask"][i] & np.isfinite(P[i]) & np.isfinite(real[i])
            if m.sum() >= 30:
                out.append((ts[i] // 86400, pd.Series(P[i][m]).rank().corr(pd.Series(real[i][m]).rank())))
        d = pd.DataFrame(out, columns=["d", "ic"]).groupby("d")["ic"].mean()
        return d
    icd, icv = ic(disc_rows), ic(val_rows)
    sign = 1.0 if icd.mean() >= 0 else -1.0
    res = {**h, "sign": sign, "disc_ic": float(icd.mean()), "val_ic": float(icv.mean()), "val_ic_ci": L.boot_ci(icv.to_numpy()) if len(icv) > 20 else None}
    if h["target"] in BINARY:
        from sklearn.metrics import roc_auc_score
        yb = tg[h["target"]]
        for tag, rows in (("disc", disc_rows), ("val", val_rows)):
            m = rows[:, None] & tg["mask"] & np.isfinite(P) & np.isfinite(yb)
            res[f"{tag}_auc"] = float(roc_auc_score(yb[m], P[m])) if m.sum() > 100 and 0 < yb[m].mean() < 1 else None
    F = sign * full
    for tag, per in (("disc", (BLOCKS[0], VAL0)), ("val", (VAL0, BLOCKS[-1]))):
        if h["target"] == "xs72":
            import b18_disc2 as D2
            rows = np.flatnonzero((ts_all % (8 * 3600) == 0) & (ts_all >= per[0]) & (ts_all < per[1]))[::9]
            b = D2.book(F, rows, 72)
            day = pd.Series(b["net"].to_numpy() / 3.0, index=b["ts"] // 86400)          # per-72h net spread over 3 days
        else:
            ls = L.long_short(F, L.eval_rows(per))
            day = ls.groupby(ls.index // 86400)["net"].sum()
        day = day.dropna()
        res[f"{tag}_net_day"] = float(day.mean()) if len(day) else None
        res[f"{tag}_net_ci"] = L.boot_ci(day.to_numpy()) if len(day) > 20 else None
        res[f"{tag}_sharpe"] = float(day.mean() / day.std() * np.sqrt(365)) if len(day) > 20 and day.std() > 0 else None
        if tag == "disc" and len(day) > 30:
            res["disc_p"] = DE.p_two_sided(day.to_numpy())
    return res


def report():
    rows = [json.load(open(p)) for p in sorted(OUT.glob("H*.json"))]
    if not rows:
        return
    ok = [r for r in rows if r.get("disc_p") is not None]
    sel = DE.bh([r["disc_p"] for r in ok], 0.10)
    for r, s in zip(ok, sel):
        ci = r.get("val_net_ci") or [0, 0]
        r["disc_bh"] = bool(s)
        r["pass"] = bool(s and ci[0] > 0 and np.sign(r["val_net_day"]) == np.sign(r["disc_net_day"]))
    df = pd.DataFrame(rows)
    cols = ["id", "target", "features", "model", "disc_ic", "val_ic", "disc_net_day", "val_net_day", "val_net_ci", "val_sharpe", "disc_bh", "pass", "val_auc", "seconds"]
    df[[c for c in cols if c in df]].to_csv(OUT / "summary.csv", index=False)
    Ls = [f"# B19 ML hypotheses: {len(rows)}/100 run, {int(df.get('pass', pd.Series(dtype=bool)).sum())} pass", "",
          "| id | target | features | model | val IC | disc net/day | val net/day | val CI | val Sharpe | BH | pass |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: -(r.get("val_sharpe") or -99)):
        ci = r.get("val_net_ci") or [np.nan, np.nan]
        Ls.append(f"| {r['id']} | {r['target']} | {r['features']} | {r['model']} | {r.get('val_ic', np.nan):+.4f} | {(r.get('disc_net_day') or 0)*1e4:+.1f}bp | "
                  f"{(r.get('val_net_day') or 0)*1e4:+.1f}bp | [{ci[0]*1e4:+.1f}, {ci[1]*1e4:+.1f}] | {r.get('val_sharpe') or 0:+.2f} | {'Y' if r.get('disc_bh') else '-'} | {'PASS' if r.get('pass') else '-'} |")
    (OUT / "summary.md").write_text("\n".join(Ls) + "\n")
    print("\n".join(Ls[:25]))


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "run"
    if cmd == "register":
        register(); return
    if cmd == "report":
        report(); return
    ids = set(sys.argv[2:])
    order = sorted(grid(), key=lambda h: (MODELS.index(h["model"]) >= 3, h["features"] != "base", h["id"]))   # fast models first
    for h in order:
        if ids and h["id"] not in ids:
            continue
        r = run_one(h)
        print(h["id"], h["target"], h["features"], h["model"], json.dumps({k: (round(v, 5) if isinstance(v, float) else v) for k, v in r.items()
              if k in ("val_ic", "disc_net_day", "val_net_day", "val_sharpe", "seconds")}), flush=True)
        report()


if __name__ == "__main__":
    main()
